title: Philgineer
iconURL: assets/my-icon.png
# theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  blog: 국문과 공대생
  github: philgineer

plugins:
 - jekyll-feed
 - jekyll-seo-tag

#math latex
markdown: kramdown
kramdown:
    math_engine: katex

### comments & analytics
google_analytics: UA-NNNNNNNN-N
