title: Philgineer
iconURL: assets/my-icon.png
# theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  blog: 국문과 공대생
  github: philgineer

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
